[38;5;70m// Generated by the Tensor Algebra Compiler (tensor-compiler.org)[0m

int compute(taco_tensor_t *C, taco_tensor_t *A, taco_tensor_t *B) {
  int C1_dimension = (int)(C->dimensions[0]);
  int C2_dimension = (int)(C->dimensions[1]);
  double* restrict C_vals = (double*)(C->vals);
  int A1_dimension = (int)(A->dimensions[0]);
  int* restrict A2_pos = (int*)(A->indices[1][0]);
  int* restrict A2_crd = (int*)(A->indices[1][1]);
  double* restrict A_vals = (double*)(A->vals);
  int B1_dimension = (int)(B->dimensions[0]);
  int* restrict B2_pos = (int*)(B->indices[1][0]);
  int* restrict B2_crd = (int*)(B->indices[1][1]);
  double* restrict B_vals = (double*)(B->vals);

  #pragma omp parallel for schedule(static)
  [38;5;204mfor[0m ([38;5;204mint32_t[0m pC = [38;5;67m0[0m[38;5;204m; [0mpC < (C1_dimension * C2_dimension)[38;5;204m; [0mpC++) {
    C_vals[pC] = [38;5;67m0.0[0m;
  }

  #pragma omp parallel for schedule(runtime)
  [38;5;204mfor[0m ([38;5;204mint32_t[0m i = [38;5;67m0[0m[38;5;204m; [0mi < A1_dimension[38;5;204m; [0mi++) {
    [38;5;204mfor[0m ([38;5;204mint32_t[0m kA = A2_pos[i][38;5;204m; [0mkA < A2_pos[(i + [38;5;67m1[0m)][38;5;204m; [0mkA++) {
      [38;5;204mint32_t[0m k = A2_crd[kA];
      [38;5;204mfor[0m ([38;5;204mint32_t[0m jB = B2_pos[k][38;5;204m; [0mjB < B2_pos[(k + [38;5;67m1[0m)][38;5;204m; [0mjB++) {
        [38;5;204mint32_t[0m j = B2_crd[jB];
        [38;5;204mint32_t[0m jC = i * C2_dimension + j;
        C_vals[jC] = C_vals[jC] + A_vals[kA] * B_vals[jB];
      }
    }
  }
  return 0;
}

